// iso2 = ISO 3166-1 alpha-2 code, used both as the form value and to build
// flag image URLs (flagcdn.com — free, no API key, no npm install needed).
//
// NOTE: this is a practical ~60-country subset, not the full ISO-3166 list
// of 249 territories. If you need full coverage, swap this array for a
// package like `world-countries` or `country-codes-list` from npm — the
// PhoneInput component below only needs { iso2, name, callingCode } per
// entry, so it'll drop in without changing the component itself.
export const countries = [
    { iso2: "AF", name: "Afghanistan", callingCode: "+93" },
    { iso2: "AL", name: "Albania", callingCode: "+355" },
    { iso2: "DZ", name: "Algeria", callingCode: "+213" },
    { iso2: "AS", name: "American Samoa", callingCode: "+1684" },
    { iso2: "AD", name: "Andorra", callingCode: "+376" },
    { iso2: "AR", name: "Argentina", callingCode: "+54" },
    { iso2: "AU", name: "Australia", callingCode: "+61" },
    { iso2: "AT", name: "Austria", callingCode: "+43" },
    { iso2: "BH", name: "Bahrain", callingCode: "+973" },
    { iso2: "BD", name: "Bangladesh", callingCode: "+880" },
    { iso2: "BE", name: "Belgium", callingCode: "+32" },
    { iso2: "BR", name: "Brazil", callingCode: "+55" },
    { iso2: "BN", name: "Brunei", callingCode: "+673" },
    { iso2: "KH", name: "Cambodia", callingCode: "+855" },
    { iso2: "CA", name: "Canada", callingCode: "+1" },
    { iso2: "CN", name: "China", callingCode: "+86" },
    { iso2: "DK", name: "Denmark", callingCode: "+45" },
    { iso2: "EG", name: "Egypt", callingCode: "+20" },
    { iso2: "FI", name: "Finland", callingCode: "+358" },
    { iso2: "FR", name: "France", callingCode: "+33" },
    { iso2: "DE", name: "Germany", callingCode: "+49" },
    { iso2: "GR", name: "Greece", callingCode: "+30" },
    { iso2: "HK", name: "Hong Kong", callingCode: "+852" },
    { iso2: "IN", name: "India", callingCode: "+91" },
    { iso2: "ID", name: "Indonesia", callingCode: "+62" },
    { iso2: "IE", name: "Ireland", callingCode: "+353" },
    { iso2: "IL", name: "Israel", callingCode: "+972" },
    { iso2: "IT", name: "Italy", callingCode: "+39" },
    { iso2: "JP", name: "Japan", callingCode: "+81" },
    { iso2: "KW", name: "Kuwait", callingCode: "+965" },
    { iso2: "MY", name: "Malaysia", callingCode: "+60" },
    { iso2: "MX", name: "Mexico", callingCode: "+52" },
    { iso2: "MM", name: "Myanmar", callingCode: "+95" },
    { iso2: "NP", name: "Nepal", callingCode: "+977" },
    { iso2: "NL", name: "Netherlands", callingCode: "+31" },
    { iso2: "NZ", name: "New Zealand", callingCode: "+64" },
    { iso2: "NO", name: "Norway", callingCode: "+47" },
    { iso2: "OM", name: "Oman", callingCode: "+968" },
    { iso2: "PK", name: "Pakistan", callingCode: "+92" },
    { iso2: "PH", name: "Philippines", callingCode: "+63" },
    { iso2: "PL", name: "Poland", callingCode: "+48" },
    { iso2: "PT", name: "Portugal", callingCode: "+351" },
    { iso2: "QA", name: "Qatar", callingCode: "+974" },
    { iso2: "RU", name: "Russia", callingCode: "+7" },
    { iso2: "SA", name: "Saudi Arabia", callingCode: "+966" },
    { iso2: "SG", name: "Singapore", callingCode: "+65" },
    { iso2: "ZA", name: "South Africa", callingCode: "+27" },
    { iso2: "KR", name: "South Korea", callingCode: "+82" },
    { iso2: "ES", name: "Spain", callingCode: "+34" },
    { iso2: "LK", name: "Sri Lanka", callingCode: "+94" },
    { iso2: "SE", name: "Sweden", callingCode: "+46" },
    { iso2: "CH", name: "Switzerland", callingCode: "+41" },
    { iso2: "TW", name: "Taiwan", callingCode: "+886" },
    { iso2: "TH", name: "Thailand", callingCode: "+66" },
    { iso2: "TR", name: "Turkey", callingCode: "+90" },
    { iso2: "AE", name: "United Arab Emirates", callingCode: "+971" },
    { iso2: "GB", name: "United Kingdom", callingCode: "+44" },
    { iso2: "US", name: "United States", callingCode: "+1" },
    { iso2: "VN", name: "Vietnam", callingCode: "+84" },
];